language: cpp
compiler:
    - g++
    - clang++
before_install:
    - sudo apt-get install libboost-dev libboost-program-options-dev libboost-system-dev
script:  
    - mkdir -p build
    - cd build  
    - cmake .. && make && cd .. && python testagg.py
